---
title: "CodesRUs Final Report"
authors: "Daniel Diaz, Ganesh Ghimire, Rose Mesina, and Michael Womble"
date: "March 9, 2022"
output:
  html_document: 
    prettydoc::html_pretty:
      theme: cayman
    code_folding: hide
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
library(ggplot2)
library(ggsoccer)
library(dplyr)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

# Determining Which Variables Contribute to Shot Success
```{r loading data, include=FALSE}
#Load Event data from each competition as a dataframe
england<-data.frame(read.csv('./datasets/events_England_new.csv'))
england$competition <- "England"

italy<-data.frame(read.csv('./datasets/events_Italy_new.csv'))
italy$competition <- "Italy"

germany<-data.frame(read.csv('./datasets/events_Germany_new.csv'))
germany$competition <- "Germany"

france<-data.frame(read.csv('./datasets/events_France_new.csv'))
france$competition <- "France"

spain<-data.frame(read.csv('./datasets/events_Spain_new.csv'))
spain$competition <- "Spain"

european<-data.frame(read.csv('./datasets/events_European_Championship_new.csv'))
european$competition <- "European"

worldcup<-data.frame(read.csv('./datasets/events_World_Cup_new.csv'))
worldcup$competition <- "World Cup"
                     
#Append dataframes into a single dataframe from which to draw.
event_data<-rbind(england, italy, germany, france, spain, european, worldcup)
```

## Chapter 1: Introduction

## Chapter 2: Data Set Overview
```{r}

```
## Chapter 3: Exploratory Data Analysis

## Chapter 4: 

## Chapter 5: Modelling Shot Success

## Chapter 6: Conclusions

