---
title: "CodesRUs_midterm"
output: html_document
---

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
library(ggplot2)
library(ggsoccer)
library(rayshader)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

## R Markdown

```{r load data}
#Load Event data from each competition as a dataframe
england<-data.frame(read.csv('./datasets/events_England.csv'))
italy<-data.frame(read.csv('./datasets/events_Italy.csv'))
germany<-data.frame(read.csv('./datasets/events_Germany.csv'))
france<-data.frame(read.csv('./datasets/events_France.csv'))
spain<-data.frame(read.csv('./datasets/events_Spain.csv'))
european<-data.frame(read.csv('./datasets/events_European_Championship.csv'))
worldcup<-data.frame(read.csv('./datasets/events_World_Cup.csv'))
event_data<-rbind(england, italy, germany, france, spain, european, worldcup)
```

```{r combine data frames}
#Append dataframes into a single dataframe from which to draw.
event_data<-rbind(england, italy, germany, france, spain, european, worldcup)
```

```{r check combined dataset}
#Check structure and summary statistics
str(event_data)
summary(event_data)
head(event_data)
```
After combining datasets from each competition, we observe 3,251,294 events. We continue by examining each event.

```{r pull shots, goals, assist, and key passes data}
#Collect shots, goals, assists, and key passes into their own dataframes
shots<-subset(event_data, Event.Name=='Shot')
goals<-subset(shots, Tag.1=='Goal')
assists<-subset(event_data, Tag.1=='Assist')
key_passes<-subset(event_data, Tag.1=='Key pass')
```

```{r}
shots_hist<-ggplot(shots, aes(x=x.Start, y=y.Start)) +
  geom_histogram() +
  scale_fill_viridis_c(option='C')
plot_gg(shots_hist, multicore=TRUE)
```
