---
title: "CodesRUs_midterm"
output: html_document
---

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(iZID)
library(ggplot2)
library(ggsoccer)
library(rayshader)
setwd("D:/peter/admin/Music/New Folder")
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

## R Markdown

```{r load data}
#Load Event data from each competition as a dataframe
england<-data.frame(read.csv('./datasets/events_England.csv'))
italy<-data.frame(read.csv('./datasets/events_Italy.csv'))
germany<-data.frame(read.csv('./datasets/events_Germany.csv'))
france<-data.frame(read.csv('./datasets/events_France.csv'))
spain<-data.frame(read.csv('./datasets/events_Spain.csv'))
european<-data.frame(read.csv('./datasets/events_European_Championship.csv'))
worldcup<-data.frame(read.csv('./datasets/events_World_Cup.csv'))
event_data<-rbind(england, italy, germany, france, spain, european, worldcup)
```

```{r combine data frames}
#Append dataframes into a single dataframe from which to draw.
event_data<-rbind(england, italy, germany, france, spain, european, worldcup)
```

```{r pull shots, goals, assist, and key passes data}
#Collect shots, goals, assists, and key passes into their own dataframes
shots<-subset(event_data, Event.Name=='Shot')
goals<-subset(shots, Tag.1=='Goal')
assists<-subset(event_data, Tag.1=='Assist')
key_passes<-subset(event_data, Tag.1=='Key pass')
```

```{r}

autoEDA <- function(x,
                    y = NULL,
                    IDFeats = NULL,
                    sampleRate = 1,
                    outcomeType = "automatic",
                    maxUniques = 150,
                    maxLevels = 250,
                    removeConstant = TRUE,
                    removeZeroSpread = TRUE,
                    removeMajorityMissing = TRUE,
                    imputeMissing = TRUE,
                    clipOutliers = TRUE,
                    minLevelPercentage = 0.025,
                    predictivePower = TRUE,
                    outlierMethod = "tukey",
                    lowPercentile = 0.01,
                    upPercentile = 0.99,
                    plotCategorical = "stackedBar",
                    plotContinuous = "histogram",
                    bins = 20,
                    rotateLabels = FALSE,
                    colorTheme = 1,
                    theme = 2,
                    color = "#26A69A",
                    transparency = 1,
                    outputPath = NULL,
                    filename = "ExploratoryPlots",
                    returnPlotList = FALSE,
                    verbose = TRUE){
  
  # LIBRARIES
  libExists <- function(x){
    if(!require(x,character.only = TRUE)){
      install.packages(x,dep = TRUE)
    }
    
    if(!require(x,character.only = TRUE)){
      stop("Package not found")
    }
  }
  libExists("ggplot2")
  libExists("RColorBrewer")
  
  library(RColorBrewer)
  library(ggplot2)
  
  # SETTINGS
  options(scipen = 999)
  set.seed(1991)
  
  x <- as.data.frame(x)
  
  # ERROR HANDLING
  if (is.null(outputPath) == FALSE){
    PDFPath = paste(outputPath, "/", filename,".pdf", sep = "")
    pdf(file = PDFPath)
  }
  
  if(maxLevels < 5){
    warning("Invalid 'maxLevels' value, defaulting")
    maxLevels <- 25
  }
  
  if(is.null(y) == FALSE & class(y) != "character"){
    stop("Outcome variable should be a character value of a variable name that exists in data")
  }
  
  if(is.null(y) == FALSE & length(which(y %in% names(x))) == 0){
    stop("Outcome variable does not exist in data")
  }
  
  if(transparency < 0 | transparency > 1){
    warning("Invalid 'transparency' value, defaulting")
    transparency <- 1
  }
  
  if(plotCategorical %in% c("stackedBar","bar","groupedBar")){
    err <- ""
  } else {
    warning("Invalid 'plotCategorical' value, defaulting")
    plotCategorical <- "stackedBar"
  }
  
  if(plotContinuous %in% c("boxplot","histogram","density","qqplot")){
    err <- ""
  } else {
    warning("Invalid 'plotContinuous' value, defaulting")
    plotContinuous <- "histogram"
  }
  
  if(bins < 0){
    warning("Invalid 'bins' value, defaulting")
    bins <- 20
  }
  
  if(theme %in% c(1,2)){
    err <- ""
  } else {
    warning("Invalid 'theme' value, defaulting")
    theme <- 2
  }
  
  if(class(color) != "character"){
    warning("Invalid 'color' value, needs to be a character string, defaulting")
    color <- "#26A69A"
  }
  
  if(sampleRate < 0 | sampleRate > 1){
    warning("Invalid 'sampleRate' value, defaulting")
    sampleRate <- 1
  }
  
  if(plotContinuous == "density" & is.null(y) == FALSE){
    transparency <- 0.7
  }
  
  # DECLARE GLOBAL VARIABLES
  plots <- list()
  
  # DECLARE FUNCTIONS
  boxplot_XY <- function(df, x, y, rotateLabels = FALSE, alpha = 0.5, theme = 1){
    p <- ggplot(data = df, aes(x = df[,y], y = df[,x], color = df[,y])) +
      geom_boxplot(lwd = 1,outlier.colour = "black", outlier.shape = 16, outlier.size = 2, alpha = alpha) +
      labs(x = y, y = x) +
      ggtitle(paste0("Distribution: ",x," By ",y)) +
      guides(fill = FALSE, colour = FALSE) +
      scale_color_manual(values = colors) +
      stat_summary(fun.y = mean, geom="point",colour="gray43", size=3)
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  density_XY <- function(df, x, y, alpha = 0.5, theme = 1){
    p <- ggplot(data = df, aes(x = df[,x], fill = df[,y], color = df[,y])) +
      geom_density(alpha = alpha) +
      labs(x = x, y = "Density") +
      ggtitle(paste0("Distribution: ",x," By ",y)) +
      guides(colour=FALSE, fill = guide_legend(title=y)) +
      scale_fill_manual(values = colors) +
      scale_color_manual(values = colors)
    
    if(theme == 2){
      p <- p + theme_classic()
    }
    
    return(p)
  }
  
  histogram_XY <- function(df, x, y, alpha = 0.5, nrBins = 15, theme = 1){
    p <- ggplot(data = df, aes(x = df[,x], fill = df[,y])) +
      geom_histogram(bins = nrBins, alpha = alpha, color = "gray") +
      labs(x = x, y = "Frequency") +
      ggtitle(paste0("Distribution: ",x," By ",y)) +
      guides(colour=FALSE, fill = guide_legend(title=y)) +
      scale_fill_manual(values = colors) +
      scale_color_manual(values = colors)
    
    if(theme == 2){
      p <- p + theme_classic()
    }
    
    return(p)
  }
  
  qqplot_groupedXY <- function(df, x, y, alpha = 0.5, theme = 1){
    p <- ggplot(data = df, aes(x = seq(1:nrow(df)), y = df[,x], color = df[,y])) +
      geom_point(alpha = alpha) +
      labs(x = "Observation", y = x) +
      ggtitle(paste0("Distribution: ", x ," By ",y)) +
      guides(colour=guide_legend(title=y), fill = FALSE) +
      scale_color_manual(values = colors)
    
    if(theme == 2){
      p <- p + theme_classic()
    }
    
    return(p)
  }
  
  qqplot_XY <- function(df,x,y,alpha = 0.5, theme = 1, color = "steelblue"){
    p <- ggplot(data = df, aes(x = df[,x], y = df[,y])) +
      geom_point(color = color,alpha = alpha) +
      labs(x = x, y = y) +
      ggtitle(paste0("Distribution: ", x ," By ",y))
    
    if(theme == 2){
      p <- p + theme_classic()
    }
    
    return(p)
  }
  
  percentageXY_bar <- function(df, x, y, rotateLabels = FALSE, alpha = 0.5, theme = 1){
    p <- ggplot(data = df, aes(x = df[,x], fill = df[,y])) +
      geom_bar(aes(y = (..count..)/sum(..count..)), alpha = alpha) +
      scale_y_continuous(labels=scales::percent) +
      labs(x = x, y = "Relative Frequency") +
      ggtitle(paste0("Distribution: ",x," By ",y)) +
      guides(fill=guide_legend(title=y)) +
      scale_fill_manual(values = colors)
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
      
    }
    
    return(p)
  }
  
  percentageXY_groupedBar <- function(df, x, y, rotateLabels = FALSE, alpha = 0.5, theme = 1){
    p <- ggplot(data = df, aes(x = df[,x], fill = df[,x])) +
      geom_bar(aes(y = (..count..)/sum(..count..)), alpha = alpha) +
      scale_y_continuous(labels=scales::percent) +
      labs(x = x, y = "Relative Frequency") +
      ggtitle(paste0("Distribution: ",x," By ",y)) +
      theme(legend.position="none") +
      facet_grid(~df[,y]) +
      scale_fill_manual(values = colors)
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    }
    
    if(theme == 2){
      p <- p + theme_classic() + theme(legend.position="none")
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  percentageXY_stackedBar <- function(df, x, y, rotateLabels = FALSE, alpha = 0.5, theme = 1){
    p <- ggplot(data = df, aes(x = df[,x], fill = df[,y])) +
      geom_bar(aes(y = (..count..)/sum(..count..)), position = "fill", alpha = alpha) +
      scale_y_continuous(labels=scales::percent) +
      labs(x = x, y = "Relative Frequency") +
      ggtitle(paste0("Distribution: ",x," By ",y)) +
      guides(fill=guide_legend(title=y)) +
      scale_fill_manual(values = colors)
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  percentageX_bar <- function(df,x,rotateLabels = FALSE,alpha = 0.5,color = "steelblue", theme = 1){
    p <- ggplot(data = df, aes(x = df[,x])) +
      geom_bar(aes(y = (..count..)/sum(..count..)), fill = color, alpha = alpha) +
      scale_y_continuous(labels=scales::percent) +
      labs(x = x, y = "Relative Frequency") +
      ggtitle(paste0("Distribution: ",x))
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + guides(fill=guide_legend(title=y))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  # 1.2 CONTINUOUS VARIABLES
  histogram_X <- function(df,x,color = "steelblue",nrBins = 15,alpha = 0.5, theme = 1,rotateLabels = FALSE){
    p <- ggplot(data = df, aes(x = df[,x])) +
      geom_histogram(bins = nrBins, alpha = alpha, fill = color, color = "gray") +
      ggtitle(paste0("Distribution: ",x)) +
      labs(x = x, y = "Frequency") +
      theme(legend.title=element_blank())
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + guides(fill=guide_legend(title=y))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  density_X <- function(df,x,color = "steelblue",alpha = 0.5, theme = 1,rotateLabels = FALSE){
    p <- ggplot(data = df, aes(x = df[,x])) +
      geom_density(alpha = alpha, fill = color, color = color) +
      ggtitle(paste0("Distribution: ",x)) +
      labs(x = x, y = "Density") +
      theme(legend.title=element_blank())
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + guides(fill=guide_legend(title=y))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  qqplot_X <- function(df, x, alpha = 0.5, theme = 1, color = "steelblue",rotateLabels = FALSE){
    p <- ggplot(data = df, aes(x = seq(1:nrow(df)), y = df[,x])) +
      geom_point(color = color,alpha = alpha) +
      labs(x = "Observation", y = x) +
      ggtitle(paste0("Distribution: ", x))
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + guides(fill=guide_legend(title=y))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  boxplot_X <- function(df,x,color = "steelblue",alpha = 0.5, theme = 1,rotateLabels = FALSE){
    p <- ggplot(data = df, aes(x = factor(0), y = df[,x])) +
      geom_boxplot(lwd = 1,outlier.colour = "black", outlier.shape = 16, outlier.size = 2, color = color, alpha = alpha) +
      theme(axis.text.x = element_blank()) +
      ggtitle(paste0("Distribution: ",x)) +
      labs(x = "", y = x)
    
    if(rotateLabels == TRUE){
      p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + guides(fill=guide_legend(title=y))
    }
    
    if(theme == 2){
      p <- p + theme_classic()
      
      if(rotateLabels == TRUE){
        p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }
    
    return(p)
  }
  
  # COLOR THEMES
  if(verbose == TRUE){
    cat("autoEDA | Setting color theme \n")
  }
  
  tol8qualitative <- c("#332288", "#88CCEE", "#44AA99", "#117733", "#999933", "#DDCC77", "#CC6677","#AA4499")
  set8equal <- c("#66C2A5", "#8DA0CB", "#A6D854", "#B3B3B3", "#E5C494", "#E78AC3", "#FC8D62", "#FFD92F")
  redmono = c("#99000D", "#CB181D", "#EF3B2C", "#FB6A4A", "#FC9272", "#FCBBA1", "#FEE0D2")
  greenmono = c("#005A32", "#238B45", "#41AB5D", "#74C476", "#A1D99B", "#C7E9C0", "#E5F5E0")
  bluemono = c("#084594", "#2171B5", "#4292C6", "#6BAED6", "#9ECAE1", "#C6DBEF", "#DEEBF7")
  greymono = c("#000000","#252525", "#525252", "#737373", "#969696", "#BDBDBD", "#D9D9D9")
  
  theme1 <- c(brewer.pal(9,"Set1"),brewer.pal(12,"Paired"))
  theme2 <- c(brewer.pal(12,"Paired"),brewer.pal(8,"Accent"))
  theme3 <- c(brewer.pal(8,"Dark2"),set8equal,tol8qualitative)
  theme4 <- c("#4527A0","#B39DDB",bluemono,redmono,greenmono,greymono)
  
  if(colorTheme == 1){
    colors <- theme1
  } else if(colorTheme == 2){
    colors <- theme2
  } else if(colorTheme == 3){
    colors <- theme3
  } else if(colorTheme == 4){
    colors <- theme4
  } else {
    colors <- colorTheme
  }
  
  # SAMPLE DATA
  ind <- sample(nrow(x),sampleRate*nrow(x),replace = F)
  x <- x[ind,]
  
  # REMOVE ID FEATURES
  if(is.null(IDFeats) == FALSE){
    if(verbose == TRUE){
      cat("autoEDA | Removing ID features \n")
    }
    x <- x[,setdiff(names(x),IDFeats)]
  }
  
  # GET OVERVIEW OF DATA
  overview <- dataOverview(x,
                           outlierMethod = outlierMethod,
                           upPercentile = upPercentile,
                           lowPercentile = lowPercentile,
                           minLevelPercentage = minLevelPercentage)
  
  # REMOVE CONSTANT FEATURES
  if(removeConstant == TRUE){
    if(verbose == TRUE){
      cat("autoEDA | Removing constant features \n")
    }
    remove <- as.character(overview[which(overview$ConstantFeature == "Yes"),1])
    x <- x[,setdiff(names(x),remove)]
    if(verbose == TRUE){
      if(length(remove) == 1){
        cat(paste0("autoEDA | ",length(remove)," constant feature removed \n"))
      } else {
        cat(paste0("autoEDA | ",length(remove)," constant features removed \n"))
      }
    }
  }
  
  # REMOVE ZERO SPREAD FEATURES
  if(removeZeroSpread == TRUE){
    remove <- as.character(overview[which(overview$ZeroSpreadFeature == "Yes"),1])
    if(is.null(y) == FALSE){
      if(verbose == TRUE){
        cat("autoEDA | Removing zero spread features \n")
      }
      remove <- setdiff(remove,y)
    }
    if(verbose == TRUE){
      if(length(remove) == 1){
        cat(paste0("autoEDA | ",length(remove)," zero spread feature removed \n"))
      } else {
        cat(paste0("autoEDA | ",length(remove)," zero spread features removed \n"))
      }
    }
    x <- x[,setdiff(names(x),remove)]
  }
  
  # REMOVE FEATURES CONTAINING MAJORITY MISSING INFORMATION
  if(removeMajorityMissing == TRUE){
    if(verbose == TRUE){
      cat("autoEDA | Removing features containing majority missing values \n")
    }
    remove <- as.character(overview[which(overview$PercentageMissing > 50),1])
    if(verbose == TRUE){
      if(length(remove) == 1){
        cat(paste0("autoEDA | ",length(remove)," majority missing feature removed \n"))
      } else {
        cat(paste0("autoEDA | ",length(remove)," majority missing features removed \n"))
      }
    }
    x <- x[,setdiff(names(x),remove)]
  }
  
  # IF FEATURES WERE REMOVED SUBSET OVERVIEW AND ORDER FRAME
  overview <- subset(overview,overview$Feature %in% names(x))
  x <- x[,names(x)]
  
  # FORMAT FEATURES
  if(is.null(y) == TRUE){
    
    for(i in 1:ncol(x)){
      if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) > maxUniques){
        x[,i] <- as.numeric(x[,i])
      } else if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) <= maxUniques){
        x[,i] <- as.character(x[,i])
      } else {
        x[,i] <- toupper(as.character(x[,i]))
      }
    }
    
  } else {
    
    for(i in 1:ncol(x)){
      if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) > maxUniques & names(x)[i] != y){
        x[,i] <- as.numeric(x[,i])
      } else if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) <= maxUniques & names(x)[i] != y){
        x[,i] <- as.character(x[,i])
      } else if(class(x[,i]) %in% c("factor","character") & names(x)[i] != y){
        x[,i] <- toupper(as.character(x[,i]))
      }
    }
    
  }
  
  # GET OVERVIEW OF DATA
  overview <- dataOverview(x,
                           outlierMethod = outlierMethod,
                           upPercentile = upPercentile,
                           lowPercentile = lowPercentile,
                           minLevelPercentage = minLevelPercentage)
  
  # CLEAN DATA ACCORDING TO OVERVIEW
  if(verbose == TRUE){
    cat("autoEDA | Cleaning data \n")
  }
  
  if(is.null(y) == TRUE){
    for(i in 1:ncol(x)){
      
      if(clipOutliers == TRUE & class(x[,i]) == "numeric"){
        x[,i] <- ifelse(x[,i] < overview[i,"LowerOutlierValue"], as.numeric(overview[i,"ImputationValue"]), x[,i])
        x[,i] <- ifelse(x[,i] > overview[i,"UpperOutlierValue"], as.numeric(overview[i,"ImputationValue"]), x[,i])
      }
      
      if(imputeMissing == TRUE){
        if(class(x[,i]) == "numeric"){
          x[,i] <- ifelse(is.na(x[,i]) == TRUE, as.numeric(overview[i,"ImputationValue"]), x[,i])
        } else {
          x[,i] <- ifelse(is.na(x[,i]) == TRUE, overview[i,"ImputationValue"], x[,i])
        }
      }
    }
  } else {
    for(i in 1:ncol(x)){
      
      if(clipOutliers == TRUE & class(x[,i]) == "numeric" & names(x)[i] != y){
        x[,i] <- ifelse(x[,i] < overview[i,"LowerOutlierValue"], as.numeric(overview[i,"ImputationValue"]), x[,i])
        x[,i] <- ifelse(x[,i] > overview[i,"UpperOutlierValue"], as.numeric(overview[i,"ImputationValue"]), x[,i])
      }
      
      if(imputeMissing == TRUE){
        if(class(x[,i]) == "numeric"){
          x[,i] <- ifelse(is.na(x[,i]) == TRUE, as.numeric(overview[i,"ImputationValue"]), x[,i])
        } else {
          x[,i] <- ifelse(is.na(x[,i]) == TRUE, overview[i,"ImputationValue"], x[,i])
        }
      }
    }
  }
  
  # FORMAT FEATURES
  if(is.null(y) == TRUE){
    
    for(i in 1:ncol(x)){
      if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) > maxUniques){
        x[,i] <- as.numeric(x[,i])
      } else if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) <= maxUniques){
        x[,i] <- as.factor(as.character(x[,i]))
        levels <- as.character(sort(as.numeric(levels(factor(x[,i])))))
        x[,i] <- factor(x[,i], levels = levels)
      } else {
        x[,i] <- as.factor(as.character(x[,i]))
        levels <- as.character(sort(levels(factor(x[,i]))))
        x[,i] <- factor(x[,i], levels = levels)
      }
    }
    
  } else {
    
    for(i in 1:ncol(x)){
      if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) > maxUniques & names(x)[i] != y){
        x[,i] <- as.numeric(x[,i])
      } else if(class(x[,i]) %in% c("integer","numeric") & length(unique(x[,i])) <= maxUniques & names(x)[i] != y){
        x[,i] <- as.factor(as.character(x[,i]))
        levels <- as.character(sort(as.numeric(levels(factor(x[,i])))))
        x[,i] <- factor(x[,i], levels = levels)
      } else if(class(x[,i]) %in% c("factor","character") & names(x)[i] != y){
        x[,i] <- as.factor(as.character(x[,i]))
        levels <- as.character(sort(levels(factor(x[,i]))))
        x[,i] <- factor(x[,i], levels = levels)
      }
    }
  }
  
  # SPARSE LEVELS OF CATEGORICAL FEATURES
  if(minLevelPercentage > 0 & is.null(y) == TRUE){
    if(verbose == TRUE){
      cat("autoEDA | Correcting sparse categorical feature levels \n")
    }
    
    for(i in 1:ncol(x)){
      if(class(x[,i]) %in% c("factor","character")){
        
        x[,i] <- as.character(x[,i])
        props <- as.data.frame(prop.table(table(x[,i])))
        levels <- as.character(props[which(props$Freq < minLevelPercentage),1])
        cumsumLevels <- sum(props[which(props$Freq < minLevelPercentage),2])
        
        if(cumsumLevels < minLevelPercentage){
          x[,i] <- ifelse(x[,i] %in% levels, overview[i,"Mode"], x[,i])
          x[,i] <- as.factor(as.character(x[,i]))
          levels <- as.character(sort(levels(factor(x[,i]))))
          x[,i] <- factor(x[,i], levels = levels)
        } else {
          x[,i] <- ifelse(x[,i] %in% levels, "ALL_OTHER", x[,i])
          x[,i] <- as.factor(as.character(x[,i]))
          levels <- as.character(sort(levels(factor(x[,i]))))
          x[,i] <- factor(x[,i], levels = levels)
        }
      }
    }
  } else if(minLevelPercentage > 0 & is.null(y) == FALSE){
    if(verbose == TRUE){
      cat("autoEDA | Correcting sparse categorical feature levels \n")
    }
    
    for(i in 1:ncol(x)){
      if(class(x[,i]) %in% c("factor","character") & names(x)[i] != y){
        
        x[,i] <- as.character(x[,i])
        props <- as.data.frame(prop.table(table(x[,i])))
        levels <- as.character(props[which(props$Freq < minLevelPercentage),1])
        cumsumLevels <- sum(props[which(props$Freq < minLevelPercentage),2])
        
        if(cumsumLevels < minLevelPercentage){
          x[,i] <- ifelse(x[,i] %in% levels, overview[i,"Mode"], x[,i])
          x[,i] <- as.factor(as.character(x[,i]))
          levels <- as.character(sort(levels(factor(x[,i]))))
          x[,i] <- factor(x[,i], levels = levels)
        } else {
          x[,i] <- ifelse(x[,i] %in% levels, "ALL_OTHER", x[,i])
          x[,i] <- as.factor(as.character(x[,i]))
          levels <- as.character(sort(levels(factor(x[,i]))))
          x[,i] <- factor(x[,i], levels = levels)
        }
      }
    }
  }
  
  # COMBINING CATEGORICAL LEVELS CAN CAUSE CONSTANT FEATURES
  if(removeConstant == TRUE){
    temp <- data.frame(Feature = names(x),
                       Unique = sapply(x, function(x) length(unique(x))))
    remove <- as.character(temp[which(temp$Unique == 1),1])
    if(length(remove) > 0){
      overview <- subset(overview,overview$Feature %in% names(x))
      x <- x[,names(x)]
    }
  }
  
  # REMOVE CATEGORICAL FEATURES ABOVE maxLevels VALUE
  if(is.null(y) == FALSE){
    temp <- data.frame(Feature = names(x),
                       Class = sapply(x,class),
                       Unique = sapply(x, function(x) length(unique(x))))
    temp <- subset(temp,temp$Feature != y)
    temp <- subset(temp,temp$Class %in% c("character","factor"))
    remove <- as.character(temp[which(temp$Unique > maxLevels),1])
    if(length(remove) > 0){
      overview <- subset(overview,overview$Feature %in% names(x))
      x <- x[,names(x)]
    }
  } else {
    temp <- data.frame(Feature = names(x),
                       Class = sapply(x,class),
                       Unique = sapply(x, function(x) length(unique(x))))
    temp <- subset(temp,temp$Class %in% c("character","factor"))
    remove <- as.character(temp[which(temp$Unique > maxLevels),1])
    if(length(remove) > 0){
      overview <- subset(overview,overview$Feature %in% names(x))
      x <- x[,names(x)]
    }
  }
  
  # RE-ORDER THAT OUTCOME IS FIRST
  if(is.null(y) == FALSE){
    if(verbose == TRUE){
      cat("autoEDA | Sorting features \n")
    }
    
    feats <- setdiff(names(x),y)
    feats <- c(y,feats)
    x <- x[,feats]
  }
  
  # DETERMINE OUTCOME TYPE IF Y IS GIVEN
  if(outcomeType == "automatic"){
    if(is.null(y) == FALSE){
      if(length(unique(x[,y])) == 2){
        outcomeType <- "binary"
        x[,y] <- as.factor(x[,y])
        if(verbose == TRUE){
          cat("autoEDA | Binary classification outcome detected \n")
        }
        
      } else if(length(unique(x[,y])) > 2 & length(unique(x[,y])) <= 15){
        outcomeType <- "multi"
        x[,y] <- as.factor(x[,y])
        if(verbose == TRUE){
          cat("autoEDA | Multi-class classification outcome detected \n")
        }
        
      } else {
        outcomeType <- "regression"
        x[,y] <- as.numeric(x[,y])
        if(verbose == TRUE){
          cat("autoEDA | Regression outcome detected \n")
        }
        
      }
    } else {
      outcomeType <- "none"
      if(verbose == TRUE){
        cat("autoEDA | Performing univariate analysis \n")
      }
      
    }
  } else {
    outcomeType <- outcomeType
  }
  
  if(color == "#26A69A" & outcomeType != "none"){
    color <- colors[1]
  }
  
  #CALCULATE PREDICTIVE POWER OF FEATURES
  options(warn = -1)
  if(predictivePower == TRUE & is.null(y) == FALSE){
    if(verbose == TRUE){
      cat("autoEDA | Calculating feature predictive power \n")
    }
    pp <- predictivePower(x = x,
                          y = y,
                          outcomeType = outcomeType)
    
    overview <- merge(x = overview,
                      y = pp,
                      by.x = "Feature",
                      all.x = TRUE)
    overview$PredictivePower <- ifelse(is.na(overview$PredictivePower) == TRUE, "Low", overview$PredictivePower)
    overview$PredictivePower <- factor(overview$PredictivePower, levels = c("Low","Medium","High"))
    
    pp_plot <- percentageXY_bar(df = overview, x = "PredictivePower", y = "PredictivePower", rotateLabels = rotateLabels, alpha = transparency, theme = theme) +
      ggtitle("Predictive power of features")
  }
  options(warn = 0)
  
  # VISUALIZE DATA
  if(verbose == TRUE){
    cat("autoEDA | Visualizing data \n")
  }
  
  if(outcomeType %in% c("binary","multi")){
    for(i in 1:ncol(x)){
      
      if(names(x)[i] == y){
        plots[[length(plots) + 1]] <- percentageXY_bar(df = x, x = y, y = y, rotateLabels = rotateLabels, alpha = transparency, theme = theme) +
          ggtitle("Outcome distribution")
        names(plots)[[length(plots)]] <- names(x)[i]
      }
      
      if(class(x[,i]) %in% c("character","factor") & names(x)[i] != y){
        if(plotCategorical == "bar"){
          plots[[length(plots) + 1]] <- percentageXY_bar(df = x, x = y, y = names(x)[i], rotateLabels = rotateLabels, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotCategorical == "groupedBar"){
          plots[[length(plots) + 1]] <- percentageXY_groupedBar(df = x, x = names(x)[i], y = y, rotateLabels = rotateLabels, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotCategorical == "stackedBar"){
          plots[[length(plots) + 1]] <- percentageXY_stackedBar(df = x, x = y, y = names(x)[i], rotateLabels = rotateLabels, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        }
        
      } else if(class(x[,i]) %in% c("integer","numeric") & names(x)[i] != y){
        if(plotContinuous == "boxplot"){
          plots[[length(plots) + 1]] <- boxplot_XY(df = x, x = names(x)[i], y = y, rotateLabels = rotateLabels, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "density"){
          plots[[length(plots) + 1]] <- density_XY(df = x, x = names(x)[i], y = y, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "histogram"){
          plots[[length(plots) + 1]] <- histogram_XY(df = x, x = names(x)[i], y = y, nrBins = bins, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "qqplot"){
          plots[[length(plots) + 1]] <- qqplot_groupedXY(df = x, x =  names(x)[i], y = y, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        }
      }
      
    }
  }
  
  if(outcomeType == "regression"){
    for(i in 1:ncol(x)){
      
      if(names(x)[i] == y){
        plots[[length(plots) + 1]] <- histogram_X(df = x, x = names(x)[i], nrBins = bins, color = color, alpha = transparency, theme = theme) +
          ggtitle("Outcome distribution")
        names(plots)[[length(plots)]] <- names(x)[i]
        plots[[length(plots) + 1]] <- qqplot_X(df = x, x = names(x)[i], color = color, alpha = transparency, theme = theme) +
          ggtitle("Outcome distribution")
        names(plots)[[length(plots)]] <- names(x)[i]
      }
      
      if(class(x[,i]) %in% c("character","factor") & names(x)[i] != y){
        if(plotContinuous == "boxplot"){
          plots[[length(plots) + 1]] <- boxplot_XY(df = x, x = y, y = names(x)[i], rotateLabels = rotateLabels, alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "qqplot"){
          plots[[length(plots) + 1]] <- qqplot_groupedXY(df = x, x =  y, y = names(x)[i], alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "histogram"){
          plots[[length(plots) + 1]] <- histogram_XY(df = x, x = y, y = names(x)[i], alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "density"){
          plots[[length(plots) + 1]] <- density_XY(df = x, x = y, y = names(x)[i], alpha = transparency, theme = theme)
          names(plots)[[length(plots)]] <- names(x)[i]
        }
        
      } else if(class(x[,i]) %in% c("integer","numeric") & names(x)[i] != y){
        plots[[length(plots) + 1]] <- qqplot_XY(df = x, x = names(x)[i], y = y, alpha = transparency, theme = theme, color = color)
        names(plots)[[length(plots)]] <- names(x)[i]
      }
      
    }
  }
  
  if(outcomeType == "none"){
    for(i in 1:ncol(x)){
      
      if(class(x[,i]) %in% c("character","factor")){
        plots[[length(plots) + 1]] <- percentageX_bar(df = x, x = names(x)[i], color = color, alpha = transparency, theme = theme, rotateLabels = rotateLabels)
        names(plots)[[length(plots)]] <- names(x)[i]
        
      } else if(class(x[,i]) %in% c("integer","numeric")){
        if(plotContinuous == "boxplot"){
          plots[[length(plots) + 1]] <- boxplot_X(df = x, x = names(x)[i], color = color, alpha = transparency, theme = theme, rotateLabels = rotateLabels)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "density"){
          plots[[length(plots) + 1]] <- density_X(df = x, x = names(x)[i], color = color, alpha = transparency, theme = theme, rotateLabels = rotateLabels)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "histogram"){
          plots[[length(plots) + 1]] <- histogram_X(df = x, x = names(x)[i], nrBins = bins, color = color, alpha = transparency, theme = theme, rotateLabels = rotateLabels)
          names(plots)[[length(plots)]] <- names(x)[i]
        } else if(plotContinuous == "qqplot"){
          plots[[length(plots) + 1]] <- qqplot_X(df = x, x = names(x)[i], color = color, alpha = transparency, theme = theme, rotateLabels = rotateLabels)
          names(plots)[[length(plots)]] <- names(x)[i]
        }
      }
    }
  }
  
  # ADD OVERVIEW PLOTS TO PLOT LIST BEFORE PLOTTING
  if(predictivePower == TRUE & is.null(y) == FALSE){
    plots[[length(plots) + 1]] <- pp_plot
    names(plots)[[length(plots)]] <- "PredictivePower"
  }
  
  if(returnPlotList == FALSE){
    invisible(lapply(plots,function(x) plot(x,main="some plot")))
  }
  
  for(i in 1:ncol(overview)){
    if(class(overview[,i]) %in% c("integer","numeric")){
      overview[,i] <- ifelse(is.na(overview[,i]) == TRUE,0,overview[,i])
    }
  }
  
  if (is.null(outputPath) == FALSE){
    dev.off()
    if(verbose == TRUE){
      cat(paste0("autoEDA | Output generated to ",outputPath," \n"))
      cat(paste0("autoEDA | Output contained in file name ",filename,".pdf \n"))
    }
  }
  
  if(returnPlotList == FALSE){
    rm(list = setdiff(ls(),c("overview")))
    invisible(gc())
    return(overview)
  } else {
    rm(list = setdiff(ls(),c("overview","plots","colors","color")))
    
    invisible(gc())
    return(list(overview = overview, plots = plots))
  }
}

dataOverview <- function(x,
                         outlierMethod = "tukey", # tukey or percentile
                         lowPercentile = 0.01,
                         upPercentile = 0.99,
                         minLevelPercentage = 0.025){

  if(missing(x)){
    stop("Please supply a data.frame object")
  }

  if(outlierMethod %in% c("tukey","percentile")){

  } else {
    warning("Invalid 'outlierMethod' value, defaulting")
    outlierMethod <- "tukey"
  }

  if(lowPercentile < 0 | lowPercentile > 1 | upPercentile < 0 | upPercentile > 1){
    warning("Invalid 'lowPercentile' or 'upPercentile' value, defaulting")
    lowPercentile <- 0.01
    upPercentile <- 0.99
  }

  if(minLevelPercentage < 0 | minLevelPercentage > 1){
    warning("'minLevelPercentage' is limited between 0 and 1, defaulting")
    minLevelPercentage <- 0.025
  }

  for(i in 1:ncol(x)){
    if(class(x[,i]) %in% c("factor","character")){
      x[,i] <- toupper(x[,i])
    }
  }

  x <- as.data.frame(x)

  overview <- data.frame(Feature = names(x),
                         Observations = nrow(x),
                         FeatureClass = sapply(x, class),
                         FeatureType = NA,
                         PercentageMissing = sapply(x, function(x) sum(is.na(x))),
                         PercentageUnique = sapply(x, function(x) length(unique(x))),
                         ConstantFeature = NA,
                         ZeroSpreadFeature = NA,
                         LowerOutliers = NA,
                         UpperOutliers = NA,
                         ImputationValue = NA,
                         MinValue = NA,
                         FirstQuartile = NA,
                         Median = NA,
                         Mean = NA,
                         Mode = NA,
                         ThirdQuartile = NA,
                         MaxValue = NA,
                         LowerOutlierValue = NA,
                         UpperOutlierValue = NA)

  overview$Feature <- as.character(overview$Feature)
  overview$FeatureClass <- as.character(overview$FeatureClass)
  overview$ConstantFeature <- as.character(ifelse(overview$PercentageUnique == 1,"Yes","No"))
  overview$FeatureType <- as.character(ifelse(overview$FeatureClass %in% c("factor","character"),"Categorical",
                                              ifelse(overview$FeatureClass == "integer","Discrete","Continuous")))
  overview$PercentageMissing <- round(overview$PercentageMissing / overview$Observations,4) * 100
  overview$PercentageUnique <- round(overview$PercentageUnique / overview$Observations,4) * 100

  for(i in 1:ncol(x)){

    if(overview[i,"FeatureClass"] %in% c("integer","numeric")){

      x[,i] <- as.numeric(x[,i])

    } else if(overview[i,"FeatureClass"] %in% c("character","factor")){

      x[,i] <- as.character(x[,i])

    }

    # ZERO SPREAD FEATURES
    if(overview[i,"FeatureClass"] %in% c("integer","numeric")){

      overview[i,"ZeroSpreadFeature"] <- IQR(x[,i], na.rm = TRUE)[[1]]

    }

    # IMPUTATION VALUE
    if(overview[i,"FeatureClass"] %in% c("integer","numeric")){

      overview[i,"ImputationValue"] <- as.character(median(x[,i], na.rm = TRUE))

    } else if(overview[i,"FeatureClass"] %in% c("factor","character")){

      props <- as.data.frame(prop.table(table(x[,i])))
      levels <- as.character(props[which(props$Freq < minLevelPercentage),1])
      cumsumLevels <- sum(props[which(props$Freq < minLevelPercentage),2])

      if(cumsumLevels < minLevelPercentage){
        overview[i,"ImputationValue"] <- as.character(props[which.max(props$Freq),1])
      } else {
        overview[i,"ImputationValue"] <- "ALL_OTHER"
      }
    }

    # MODE
    levels <- data.frame(table(x[,i]))
    overview[i,"Mode"] <- as.character(levels[which.max(levels$Freq),1])

    # SUMMARY STATISTICS
    if(overview[i,"FeatureClass"] %in% c("integer","numeric")){
      overview[i,"MinValue"] <- min(x[,i], na.rm = TRUE)
      overview[i,"FirstQuartile"] <- quantile(x[,i], probs = 0.25, na.rm = TRUE)[[1]]
      overview[i,"Median"] <- round(median(x[,i], na.rm = TRUE),2)
      overview[i,"Mean"] <- round(mean(x[,i], na.rm = TRUE),2)
      overview[i,"ThirdQuartile"] <- quantile(x[,i], probs = 0.75, na.rm = TRUE)[[1]]
      overview[i,"MaxValue"] <- max(x[,i], na.rm = TRUE)
    }

    # OUTLIERS
    if(overview[i,"FeatureClass"] %in% c("integer","numeric")){
      if(outlierMethod == "tukey"){

        overview[i,"LowerOutlierValue"] <- quantile(x[,i], probs = 0.25, na.rm = TRUE)[[1]] - (1.5*IQR(x[,i], na.rm = TRUE))
        overview[i,"UpperOutlierValue"] <- quantile(x[,i], probs = 0.75, na.rm = TRUE)[[1]] + (1.5*IQR(x[,i], na.rm = TRUE))

        overview[i,"LowerOutliers"] <- length(which(x[,i] < overview[i,"LowerOutlierValue"]))
        overview[i,"UpperOutliers"] <- length(which(x[,i] > overview[i,"UpperOutlierValue"]))

      } else {

        overview[i,"LowerOutlierValue"] <- quantile(x[,i], probs = lowPercentile, na.rm = TRUE)[[1]]
        overview[i,"UpperOutlierValue"] <- quantile(x[,i], probs = upPercentile, na.rm = TRUE)[[1]]

        overview[i,"LowerOutliers"] <- length(which(x[,i] < overview[i,"LowerOutlierValue"]))
        overview[i,"UpperOutliers"] <- length(which(x[,i] > overview[i,"UpperOutlierValue"]))
      }
    }
  }

  overview$ZeroSpreadFeature <- as.character(ifelse(overview$ZeroSpreadFeature == 0,"Yes","No"))
  overview$ZeroSpreadFeature <- ifelse(is.na(overview$ZeroSpreadFeature) == TRUE,"No",overview$ZeroSpreadFeature)
  overview$ImputationValue <- ifelse(overview$FeatureClass %in% c("character","factor") & overview$PercentageMissing > minLevelPercentage,"MISSING",overview$ImputationValue)

  for(i in 1:ncol(overview)){
    overview[,i] <- ifelse(is.na(overview[,i]) == TRUE,0,overview[,i])
  }
  row.names(overview) <- NULL

  return(overview)
}

predictivePower <- function(x,
                            y,
                            outcomeType = "automatic"){

options(cipen = 999)
set.seed(1991)

if(missing(x)){
  stop("Invalid 'x' value, provide a dataset")
}

if(missing(y)){
  stop("Invalid 'y' value, speficy outcome variable name as a character string")
}

if(outcomeType %in% c("automatic","binary","multi","regression")){
  err <- ""
} else {
  warning("'outcomeType' must be a valid value, see help document, defaulting")
  outcomeType <- "automatic"
}

x <- as.data.frame(x)

# DETERMINE OUTCOME TYPE
if(outcomeType == "automatic"){
  if(is.null(y) == FALSE){
    if(length(unique(x[,y])) == 2){
      outcomeType <- "binary"
      x[,y] <- as.factor(x[,y])
    } else if(length(unique(x[,y])) > 2 & length(unique(x[,y])) <= 15){
      outcomeType <- "multi"
      x[,y] <- as.factor(x[,y])
    } else {
      outcomeType <- "regression"
      x[,y] <- as.numeric(x[,y])
    }
  }
} else {
  outcomeType <- outcomeType
}

# CREATE FRAME THAT WILL HOUSE RESULTS
temp <- data.frame(Feature = names(x),
                   PredictivePowerPercentage = NA,
                   PredictivePower = NA)
options(warn = -1)
for(i in 1:ncol(x)){
  if(outcomeType == "regression"){
    feat <- x[,i]
    outcome <- x[,y]
    if(class(feat) == "numeric"){
      power <- abs(round(cor(outcome,feat, use = "complete.obs"),2))
    } else {
      feat <- as.numeric(as.factor(x[,i]))
      power <- abs(round(cor(outcome,feat, use = "complete.obs"),2))
    }
    temp[i,"PredictivePowerPercentage"] <- power
    temp[i,"PredictivePower"] <- ifelse(power <= 0.3,"Low",
                                        ifelse(power > 0.3 & power <= 0.5,"Medium","High"))
  } else {
    classes <- unique(x[,y])
    temp1 <- list()
    temp2 <- list()

    if(class(x[,i]) %in% c("integer","numeric")){
      if(names(x)[i] != y){
        for(j in 1:length(classes)){
          df <- subset(x,x[,y] == classes[j])
          temp2[[j]] <- df[,c(names(x)[i],y)]
        }

        df <- as.data.frame(do.call(rbind,temp2))
        class1 <- subset(df,df[,y] == classes[1])[[names(x)[i]]]
        rest <- subset(df,df[,y] != classes[1])
        classes <- unique(rest[,y])

        for(k in 1:length(classes)){
          compare <- subset(rest,rest[,y] == classes[k])[[names(x)[i]]]
          ks <- ks.test(class1, compare)
          temp1[[i]] <- ks$statistic[[1]]
        }

        power <- as.numeric(do.call(rbind,temp1))
        power <- round(mean(power),2)

        temp[i,"PredictivePowerPercentage"] <- power
        temp[i,"PredictivePower"] <- ifelse(power <= 0.3,"Low",
                                            ifelse(power > 0.3 & power <= 0.5,"Medium","High"))
      }
    } else {
      if(names(x)[i] != y){
        x[,i] <- as.numeric(as.factor(x[,i]))

        for(j in 1:length(classes)){
          df <- subset(x,x[,y] == classes[j])
          temp2[[j]] <- df[,c(names(x)[i],y)]
        }

        df <- as.data.frame(do.call(rbind,temp2))
        class1 <- subset(df,df[,y] == classes[1])[[names(x)[i]]]
        rest <- subset(df,df[,y] != classes[1])
        classes <- unique(rest[,y])

        for(k in 1:length(classes)){
          compare <- subset(rest,rest[,y] == classes[k])[[names(x)[i]]]
          ks <- ks.test(class1, compare)
          temp1[[i]] <- ks$statistic[[1]]
        }

        power <- as.numeric(do.call(rbind,temp1))
        power <- round(mean(power),2)

        temp[i,"PredictivePowerPercentage"] <- power
        temp[i,"PredictivePower"] <- ifelse(power <= 0.3,"Low",
                                            ifelse(power > 0.3 & power <= 0.5,"Medium","High"))
      }

    }

  }

}

temp$PredictivePowerPercentage <- temp$PredictivePowerPercentage * 100
temp$PredictivePowerPercentage <- ifelse(temp$Feature == y, NA, temp$PredictivePowerPercentage)
temp$PredictivePower <- ifelse(temp$Feature == y, NA, temp$PredictivePower)
temp <- subset(temp, temp$Feature != y)
options(warn = 0)
return(temp)
}
autoEDA(goals)
autoEDA(shots)
autoEDA(assists)
autoEDA(key_passes)
plot(goals$x.Start,goals$y.Start,main='relationship between goals and shot position')
plot((as.numeric(goals$x.End)-as.numeric(goals$x.Start))^2+(as.numeric(goals$y.End)-as.numeric(goals$y.Start))^2,main='relationship between goals and shot distance')
library(corrgram)
library(corrplot)
library(ggplot2)
corrplot(cor(goals[,sapply(goals,is.numeric)],use="complete.obs",method="pearson"))

```
